### ISSUE TITLE
Pesquisa sobre como fazer revisão sistemática.

### ISSUE THREAD

**Issue by filipemalgueiro** [filipemalgueiro/Projeto-I.A#2]
![Image](https://github.com/user-attachments/assets/a334feb6-fbd2-4217-9531-6c2e22a4e943)

**Comment by davileahy** [comment]
Para a revisão sistemática, estamos pesquisando em bases de dados científicas para encontrar artigos e estudos que estejam alinhados com o objetivo do nosso projeto.
